### ISSUE TITLE
Can't install on Windows 10

### ISSUE THREAD

**Issue by nfrik** [PytLab/gaft#1]
I was not able to install gaft on my Windows 10 machine. It worked fine without mpi4py on mac.

**Comment by PytLab** [comment]
Hello, thanks for your support to GAFT project. Could you show me more details about the error information on Mac and Windows10? I'm trying to make gaft compatible with windows 😄

**Comment by PytLab** [comment]
Hi, the gaft is now compatible with Windows10. 

For the MPI version, you should install MPI implementation like MPICH first on the platform, and then install gaft.

For more installation details, see [INSTALL.md](https://github.com/PytLab/gaft/blob/master/INSTALL.md)

**Comment by nfrik** [comment]
Perfect thank for great library!

**Comment by TsingQAQ** [comment]
Hi there,

I've faced an installtion error either.
I've downloaded the MS-MPI and install it while it said the PC already have a MPI or a newer version of that. However, when I install the gaft through:
`pip install gaft`
an error occured and it said:
 `Cannot compile MPI programs. Check your configuration`

Any suggestions of that?
Xiexie...

**Comment by PytLab** [comment]
It may seems that you didn't install MPI implementation successfully on your platform. 

This building exception may be raised when installing [mpi4py](https://pypi.python.org/pypi/mpi4py/). You can try to install mpi4py independently before installing gaft.

**Comment by TsingQAQ** [comment]
Solved Finally. 
Just a reference for everyone else facing the mpi4py installation error, if you're installing it on windows, you need to add MS-MPI's bin directory to system envirables first and the mpi4py can be installed sucessfully.
