### ISSUE TITLE
复杂问题求解内存消耗太大

### ISSUE THREAD

**Issue by kodayu** [PytLab/gaft#11]
我用遗传算法来优化机器学习参数的时候，内存消耗非常大，虽然加入mpirun后速度很快，但是50个seed一轮都跑不完，内存就完全不够用了（计算了一下，十个seed一轮约占75G），请问是什么原因呢？

**Comment by kodayu** [comment]
我检查了一下，我用两个seed跑一轮的时候，事实上运行了很多轮，不是很清楚是什么原因。。。初学遗传算法感觉都要蒙圈了，求大神指教。

**Comment by kodayu** [comment]
我刚发现有人问过和我类似的问题，就是30个seed迭代一轮，实际调用fitness函数调用了900多轮，导致内存消耗很大。

**Comment by PytLab** [comment]
你好，这个可能是我在计算种群个体适应度的时候动态的传入适应度函数导致重复的运算，我近期会尝试修复这个bug，感谢提出

**Comment by kodayu** [comment]
哦哦，我是说呢，用四个seed运行两轮，fitness函数调用了55次。不过我没看出来怎么改，还是得辛苦大神。。。

**Comment by kodayu** [comment]
还有一点，就是调用mpirun的时候fitness函数的调用会更加倍增。

**Comment by PytLab** [comment]
你好，我在刚刚的commit中修复了多余调用适应度函数的问题，你可以进行测试，有问题欢迎提出哈。另外mpirun是同时启动多个mpi进程执行，在迭代开始产生新种群的时候会按照进程数进行分割，所以调用增加是正常的，你可以看看效率有没有提升

**Comment by abcgreat11** [comment]
> 我用遗传算法来优化机器学习参数的时候，内存消耗非常大，虽然加入mpirun后速度很快，但是50个seed一轮都跑不完，内存就完全不够用了（计算了一下，十个seed一轮约占75G），请问是什么原因呢？

您好！请问您有没有尝试过将神经网络和进化计算相结合？可以加我QQ：542278416详细交流一下吗？我最近也在学习使用Python进化算法工具箱。
