### ISSUE TITLE
TypeError: register_step() got an unexpected keyword argument 'g'

### ISSUE THREAD

**Issue by sangyunxin** [PytLab/gaft#12]
使用readme当中的程序示例时报错如下：
TypeError                                 Traceback (most recent call last)
<ipython-input-13-c8b2e3093586> in <module>()
----> 1 engine.run(ng=100)

D:\Anaconda\lib\site-packages\gaft\engine.py in profiled_func(*args, **kwargs)
     43                 ps.dump_stats(filename)
     44             else:
---> 45                 result = func(*args, **kwargs)
     46             return result
     47         return profiled_func

D:\Anaconda\lib\site-packages\gaft\engine.py in run(self, ng)
    202                 msg = '{} exception is catched'.format(type(e).__name__)
    203                 self.logger.exception(msg)
--> 204             raise e
    205         finally:
    206             # Recover current generation number.

D:\Anaconda\lib\site-packages\gaft\engine.py in run(self, ng)
    196                 for a in self.analysis:
    197                     if g % a.interval == 0:
--> 198                         a.register_step(g=g, population=self.population, engine=self)
    199         except Exception as e:
    200             # Log exception info.

D:\Anaconda\lib\site-packages\gaft\mpiutil.py in _call_in_master_proc(*args, **kwargs)
    110     def _call_in_master_proc(*args, **kwargs):
    111         if mpi.is_master:
--> 112             return func(*args, **kwargs)
    113 
    114     return _call_in_master_proc

TypeError: register_step() got an unexpected keyword argument 'g'

**Comment by PytLab** [comment]
你好，这是由于我更新了analysis pluging的接口参数名称没有及时在readme里面更新导致的，你只需要把例子里面的`ng`换成`g`就可以了，现在README里也已经更新过来了。
