### ISSUE TITLE
多元函数求最值优化参数约束问题

### ISSUE THREAD

**Issue by TJUZMX** [PytLab/gaft#15]
您好，我最近正在用gaft做多参数优化遇到了问题，求解的问题如下：目标函数min A=f(x,y,m,n)，施加约束条件时，除了需要对x,y,m,n四个参数进行约束之外，还需要对参数L=g1(x,y,m,n)与K=g2(x,y,m,n)设定约束条件，这在gaft框架下如何实现呢？是否需要对种群初始化、交叉和变异函数进行修改？该如何修改呢？谢谢 : ）

**Comment by PytLab** [comment]
你是指变量还有其他的等式约束条件？

**Comment by TJUZMX** [comment]
也是不等式约束，是指由x,y,m,n四个变量计算出来的两个变量L和K也要满足一定的不等式约束条件，也就是说用于优化的变量之间存在一定的关联。

**Comment by PytLab** [comment]
这种的约束一般可以通过惩罚函数法来处理（当然也有其他方法你可以查一下相应文献)，做法可以是在你写的适应度函数里面对于不满足约束条件的可行解的适应度值添加惩罚，使其在迭代的过程中被淘汰掉。
