### ISSUE TITLE
fitness init will be overwritten when GAEngine init

### ISSUE THREAD

**Issue by minimada** [PytLab/gaft#17]
When perform engine = GAEngine(..., fitness=fitness), the fitness function will be overwritten None at GAEngine.__init__ line 135:
`self.ori_fitness, self.fitness = None, None`

I think maybe you can use
`self.ori_fitness = None if self.fitness is None else self.fitness`
instead of origin code.

**Comment by PytLab** [comment]
Yes, you're right! I will fix this bug later or you can pull request if possible :) And I will test it and merge.
