### ISSUE TITLE
关于多进程运行的问题

### ISSUE THREAD

**Issue by littletomatodonkey** [PytLab/gaft#20]
您好，我在使用`mpiexec -np 4 ex01.py`的时候(windows上是mpiexec)，发现速度比单个进程运行的速度慢了很多，我以为是进程数据广播和回收的耗时较长，就在fitness函数里面又手动添加了大量无效计算，增加单个个体的计算时间，但是还是出现并行计算时间明显大于单进程计算的时间，我想问一下这可能是什么原因哦？我的openmpi多进程编程测试没有出现问题，安装应该是没有问题的。我修改ex01.py中的fitness代码如下（只是添加了耗时计算）：

    # Define fitness function.
    @engine.fitness_register
    def fitness(indv):
        x, = indv.solution
        for ii in range(10000):
            x + 10*sin(5*x) + 7*cos(4*x)
        return x + 10*sin(5*x) + 7*cos(4*x)

希望得到您的回复，谢谢！

**Comment by PytLab** [comment]
你的种群大小是多少？你可以增加一下大小来测试一下并行效果

**Comment by littletomatodonkey** [comment]
size我设置的是100，感觉应该挺大了，可是还是没有单个进程的运行速度快2333。。

**Comment by PytLab** [comment]
1. 你要看一下你机器的核心是多少，如果是两个的话，多于两个其实并不会有很多提升
2. 你可以测试一下增大种群大小，也可以测试下example里面的例子

**Comment by abcgreat11** [comment]
> 您好，我在使用`mpiexec -np 4 ex01.py`的时候(windows上是mpiexec)，发现速度比单个进程运行的速度慢了很多，我以为是进程数据广播和回收的耗时较长，就在fitness函数里面又手动添加了大量无效计算，增加单个个体的计算时间，但是还是出现并行计算时间明显大于单进程计算的时间，我想问一下这可能是什么原因哦？我的openmpi多进程编程测试没有出现问题，安装应该是没有问题的。我修改ex01.py中的fitness代码如下（只是添加了耗时计算）：
> 
> ```
> # Define fitness function.
> @engine.fitness_register
> def fitness(indv):
>     x, = indv.solution
>     for ii in range(10000):
>         x + 10*sin(5*x) + 7*cos(4*x)
>     re

> 您好，我在使用`mpiexec -np 4 ex01.py`的时候(windows上是mpiexec)，发现速度比单个进程运行的速度慢了很多，我以为是进程数据广播和回收的耗时较长，就在fitness函数里面又手动添加了大量无效计算，增加单个个体的计算时间，但是还是出现并行计算时间明显大于单进程计算的时间，我想问一下这可能是什么原因哦？我的openmpi多进程编程测试没有出现问题，安装应该是没有问题的。我修改ex01.py中的fitness代码如下（只是添加了耗时计算）：
> 
> ```
> # Define fitness function.
> @engine.fitness_register
> def fitness(indv):
>     x, = indv.solution
>     for ii in range(10000):
>         x + 10*sin(5*x) + 7*cos(4*x)
>     return x + 10*sin(5*x) + 7*cos(4*x)
> ```
> 希望得到您的回复，谢谢！

您好，我也在研究并发进行进化计算，可以加我QQ：542278416详细交流一下吗？我最近也在学习使用Python进化算法工具箱。

**Comment by hoboly** [comment]
請問為什麼我的電腦會運行 2 組? 而不是1組data 分派給2個核心?

C:\test>mpiexec -np 2  "C:\ProgramData\Anaconda3\python.exe" ex01.py
gaft.ConsoleOutputAnalysis   INFO     Generation: 0, best fitness: 19.883
gaft.ConsoleOutputAnalysis   INFO     Generation: 0, best fitness: 24.853
gaft.ConsoleOutputAnalysis   INFO     Generation: 1, best fitness: 19.883
gaft.ConsoleOutputAnalysis   INFO     Generation: 1, best fitness: 24.854
gaft.ConsoleOutputAnalysis   INFO     Generation: 2, best fitness: 19.883
gaft.ConsoleOutputAnalysis   INFO     Generation: 2, best fitness: 24.854
gaft.ConsoleOutputAnalysis   INFO     Generation: 3, best fitness: 19.883
gaft.ConsoleOutputAnalysis   INFO     Generation: 3, best fitness: 24.854
gaft.ConsoleOutputAnalysis   INFO     Generation: 4, best fitness: 20.600
gaft.ConsoleOutputAnalysis   INFO     Generation: 4, best fitness: 24.854
gaft.ConsoleOutputAnalysis   INFO     Generation: 5, best fitness: 20.600
gaft.ConsoleOutputAnalysis   INFO     Generation: 5, best fitness: 24.854
gaft.ConsoleOutputAnalysis   INFO     Generation: 6, best fitness: 20.600
gaft.ConsoleOutputAnalysis   INFO     Generation: 6, best fitness: 24.855
gaft.ConsoleOutputAnalysis   INFO     Generation: 7, best fitness: 20.677
gaft.ConsoleOutputAnalysis   INFO     Generation: 7, best fitness: 24.855
gaft.ConsoleOutputAnalysis   INFO     Generation: 8, best fitness: 20.677
gaft.ConsoleOutputAnalysis   INFO     Generation: 9, best fitness: 20.677
gaft.ConsoleOutputAnalysis   INFO     Generation: 8, best fitness: 24.855
gaft.FitnessStore   INFO     Best fitness values are written to best_fit.py
gaft.ConsoleOutputAnalysis   INFO     Optimal solution: ([9.3212890625], 20.6766
55455888568)
gaft.ConsoleOutputAnalysis   INFO     Generation: 9, best fitness: 24.855
gaft.FitnessStore   INFO     Best fitness values are written to best_fit.py
gaft.ConsoleOutputAnalysis   INFO     Optimal solution: ([7.855224609375], 24.85
494496737466)
