### ISSUE TITLE
通过python setup.py install安装gaft不成功

### ISSUE THREAD

**Issue by zhangxiaozao** [PytLab/gaft#23]
错误信息如下：（希望得到指点，多谢！期待您的回复～）
Installed /usr/local/lib/python3.5/dist-packages/gaft-0.5.4-py3.5.egg
Processing dependencies for gaft==0.5.4
Searching for mpi4py
Reading https://pypi.org/simple/mpi4py/
Downloading https://files.pythonhosted.org/packages/31/27/1288918ac230cc9abc0da17d84d66f3db477757d90b3d6b070d709391a15/mpi4py-3.0.0.tar.gz#sha256=b457b02d85bdd9a4775a097fac5234a20397b43e073f14d9e29b6cd78c68efd7
Best match: mpi4py 3.0.0
Processing mpi4py-3.0.0.tar.gz
Writing /tmp/easy_install-y80fvzfj/mpi4py-3.0.0/setup.cfg
Running mpi4py-3.0.0/setup.py -q bdist_egg --dist-dir /tmp/easy_install-y80fvzfj/mpi4py-3.0.0/egg-dist-tmp-c4x3ge3x
/usr/bin/ld: cannot find -llmpe
collect2: error: ld returned 1 exit status
/usr/bin/ld: cannot find -lvt-mpi
collect2: error: ld returned 1 exit status
/usr/bin/ld: cannot find -lvt.mpi
collect2: error: ld returned 1 exit status
/usr/bin/ld: cannot find -lvt-mpi
collect2: error: ld returned 1 exit status
/usr/bin/ld: cannot find -lvt.mpi
collect2: error: ld returned 1 exit status
/usr/bin/ld: cannot find -lvt-hyb
collect2: error: ld returned 1 exit status
/usr/bin/ld: cannot find -lvt.ompi
collect2: error: ld returned 1 exit status
_configtest.c:2:17: fatal error: mpi.h: No such file or directory
compilation terminated.
error: Setup script exited with error: Cannot compile MPI programs. Check your configuration!!!

**Comment by abcgreat11** [comment]
> 已经装好了，忘记装openmpi了...感谢！

您好，我在pychram上安装后运行时出现MPI报错，您是在pychram上使用的吗？可以加我QQ：542278416互相交流学习一下吗？我最近也在学习使用Python遗传算法工具箱。
