### ISSUE TITLE
How to run gaft using mpi ?

### ISSUE THREAD

**Issue by clardeux** [PytLab/gaft#26]
Hi,
first, thanks a lot for your library that is very easy to use.

My optimisation problem is working well but now I would like to speed up using parallel processing with mpi.
However, I am a newbie on that things and I don't know the programming rules in the python program itself and the command to run in parralle my script.

Should it be possible to have a full example of running example1 (for example) using mpi ?

Best regards

**Comment by PytLab** [comment]
You can use `mpirun` or `mpiexec` to run the script explicitly. For example, 
``` shell
mpirun -np 2 python yourscript.py
```

**Comment by PytLab** [comment]
If you don't have any question, I will close this issue.

Thanks :)
