### ISSUE TITLE
变异或交叉后数值溢出问题

### ISSUE THREAD

**Issue by Gittry** [PytLab/gaft#27]
以整数为例：
假设chrom1 = '1000',ranges = [0,10],chrom1变异为1100则outrange,此处在库里面没看到相关处理；
同理，假设chrom2 = '0101'，与chrom1在第2位交叉，也会出现outrange；
当然，outrange异常可以在fitness中进行惩罚，但这点不得不提一下。

**Comment by 1061655504** [comment]
最近中美三大高校联合推出了全新的遗传和进化算法框架，试了一下速度比这个快几个数量级，比Matlab的工具箱还容易学。你可以试一下。

**Comment by 1061655504** [comment]
最近中美三大高校联合推出了全新的遗传和进化算法框架——Geatpy，速度很快。比Matlab的工具箱还容易学。你可以试一下。

**Comment by 1061655504** [comment]
> 以整数为例：
> 假设chrom1 = '1000',ranges = [0,10],chrom1变异为1100则outrange,此处在库里面没看到相关处理；
> 同理，假设chrom2 = '0101'，与chrom1在第2位交叉，也会出现outrange；
> 当然，outrange异常可以在fitness中进行惩罚，但这点不得不提一下。

最近中美三大高校联合推出了全新的遗传和进化算法框架——Geatpy，速度很快。比Matlab的工具箱还容易学。你可以试一下。

**Comment by abcgreat11** [comment]
> 以整数为例：
> 假设chrom1 = '1000',ranges = [0,10],chrom1变异为1100则outrange,此处在库里面没看到相关处理；
> 同理，假设chrom2 = '0101'，与chrom1在第2位交叉，也会出现outrange；
> 当然，outrange异常可以在fitness中进行惩罚，但这点不得不提一下。

我也有这个疑问。。可以加我QQ：542278416详细交流一下吗？我最近也在学习使用Python遗传算法工具箱。
