### ISSUE TITLE
可以用来解决经典的TSP问题吗？比如背包问题那种

### ISSUE THREAD

**Issue by mxdlzg** [PytLab/gaft#28]

**Comment by 1061655504** [comment]
> _No description provided._

最近中美三大高校联合推出了全新的遗传和进化算法框架——Geatpy，速度很快。比Matlab的工具箱还容易学。你可以试一下。

**Comment by PytLab** [comment]
可以，根据不同场景定义自己的适应度函数，使用遗传算法进行迭代即可
