### ISSUE TITLE
您好，运行库报错，Individual index(50) out of range

### ISSUE THREAD

**Issue by LoveSophia** [PytLab/gaft#29]
代码：
import numpy as np
from gaft import GAEngine
from gaft.components import DecimalIndividual, Population
from gaft.operators import RouletteWheelSelection, UniformCrossover, FlipBitMutation
# Analysis plugin base class.
from gaft.plugin_interfaces.analysis import OnTheFlyAnalysis
from gaft.analysis.fitness_store import FitnessStore

M_pi = np.pi
Lambda = 1
NTET = 180
dtet = M_pi / 2. / NTET
DISTEW = 2
dishD = 0.1
PiDol = M_pi * dishD / Lambda
y_opti = np.zeros(361)

# 检测最小差值是否小于0.5
def interval_verify(gene, minimum=0.5):
    for i in range(len(gene)):
        for j in gene[i:]:
            if abs(gene[i] - j) > minimum:
                return False
    return True

def lobeAMPSquare(tet):
    if abs(tet) < 10e-9:
        return 1.
    x = tet * PiDol
    y = np.sin(x) / x
    return y

# Step 1. 定义种群
# 每个基因的范围是【0~32】
indv_template = DecimalIndividual(ranges=[(-7, 8)] * 14, eps=0.005)
population = Population(indv_template=indv_template, size=50)
population.init()  # Initialize population with individuals.

# Step 2. 定义基因操作
selection = RouletteWheelSelection()
crossover = UniformCrossover(pc=0.8, pe=0.5)
mutation = FlipBitMutation(pm=0.1)

# Step 3. 初始化引擎
engine = GAEngine(population=population, selection=selection,
                  crossover=crossover, mutation=mutation,
                  analysis=[FitnessStore])

# Step 4. 定义评价函数
@engine.fitness_register
def fitness(indv):
    LesPXX = np.sort(np.array(indv.solution))
    # 先判断是否满足最小间距
    if not interval_verify(LesPXX):
        return -float('inf')
    i = -180
    while i <= 180:
        teta = i * dtet
        RepAmp = lobeAMPSquare(teta)
        sumc = 0
        ws = np.complex(0., 0.)
        for na in range(14):
            phase = 2. * M_pi * DISTEW * LesPXX[na] / Lambda * np.sin(teta)
            ws += (complex(np.cos(phase), np.sin(phase)) * RepAmp)
            sumc += 1
        y_opti[i + NTET] = ws.real ** 2 + ws.imag ** 2
        i += 1
    res = np.abs(y_opti/np.max(y_opti))
    return float(np.max(np.union1d(res[-180:-2], res[2:180])))
    # gene = np.array(indv.solution)
    # score1 = np.sin((np.pi * d * theta) / lamda) / (np.pi * d / lamda)
    # score2 = np.exp(i * 2 * np.pi * theta * (d + gene) / lamda)
    # score3 = score1 * score2
    # # a - 实部平方 + 虚部平方
    # score = np.sum((score3.real) ** 2 + (score3.imag) ** 2)
    # # b - 用绝对值
    # # score = np.sum(np.abs(score3))
    # return float(-score)  # 这个库只有最小化，我们需要最大化，因此加一个负号

# Step 5. 定义动态分析, 不注释会报错
@engine.analysis_register
class ConsoleOutputAnalysis(OnTheFlyAnalysis):
    interval = 1
    master_only = True

    def register_step(self, g, population, engine):
        best_indv = population.best_indv(engine.fitness)
        msg = 'Generation: {}, best fitness: {:.3f}'.format(g, engine.ori_fmax)
        self.logger.info(msg)

    def finalize(self, population, engine):
        best_indv = population.best_indv(engine.fitness)
        x = best_indv.solution
        y = engine.ori_fmax
        msg = 'Optimal solution: ({}, {})'.format(x, y)
        self.logger.info(msg)
        print('sort:', np.sort(x))

# Step 6. 运行
if '__main__' == __name__:
    engine.run(5)

报错内容：

C:\Users\liu\AppData\Local\Programs\Python\Python36\python.exe C:/Users/liu/Desktop/1.py
gaft.GAEngine   ERROR    IndexError exception is catched
Traceback (most recent call last):
  File "C:\Users\liu\AppData\Local\Programs\Python\Python36\lib\site-packages\gaft\engine.py", line 182, in run
    parents = self.selection.select(self.population, fitness=self.fitness)
  File "C:\Users\liu\AppData\Local\Programs\Python\Python36\lib\site-packages\gaft\plugin_interfaces\metaclasses.py", line 157, in _wrapped_select
    return select(self, population, fitness)
  File "C:\Users\liu\AppData\Local\Programs\Python\Python36\lib\site-packages\gaft\operators\selection\roulette_wheel_selection.py", line 39, in select
    father = population[father_idx]
  File "C:\Users\liu\AppData\Local\Programs\Python\Python36\lib\site-packages\gaft\components\population.py", line 168, in __getitem__
    raise IndexError('Individual index({}) out of range'.format(key))
IndexError: Individual index(50) out of range
gaft.FitnessStore   INFO     Best fitness values are written to best_fit.py
gaft.ConsoleOutputAnalysis   INFO     Optimal solution: ([-0.8799999999999999, 4.825000000000001, -1.5999999999999996, -1.0599999999999996, -3.55, -5.025, 5.870000000000001, 7.9399999999999995, -5.89, 5.234999999999999, -2.1799999999999997, 3.625, -6.375, -4.045], -inf)
sort: [-6.375 -5.89  -5.025 -4.045 -3.55  -2.18  -1.6   -1.06  -0.88   3.625
  4.825  5.235  5.87   7.94 ]
Traceback (most recent call last):
  File "C:/Users/liu/Desktop/1.py", line 106, in <module>
    engine.run(5)
  File "C:\Users\liu\AppData\Local\Programs\Python\Python36\lib\site-packages\gaft\engine.py", line 45, in profiled_func
    result = func(*args, **kwargs)
  File "C:\Users\liu\AppData\Local\Programs\Python\Python36\lib\site-packages\gaft\engine.py", line 209, in run
    raise e
  File "C:\Users\liu\AppData\Local\Programs\Python\Python36\lib\site-packages\gaft\engine.py", line 182, in run
    parents = self.selection.select(self.population, fitness=self.fitness)
  File "C:\Users\liu\AppData\Local\Programs\Python\Python36\lib\site-packages\gaft\plugin_interfaces\metaclasses.py", line 157, in _wrapped_select
    return select(self, population, fitness)
  File "C:\Users\liu\AppData\Local\Programs\Python\Python36\lib\site-packages\gaft\operators\selection\roulette_wheel_selection.py", line 39, in select
    father = population[father_idx]
  File "C:\Users\liu\AppData\Local\Programs\Python\Python36\lib\site-packages\gaft\components\population.py", line 168, in __getitem__
    raise IndexError('Individual index({}) out of range'.format(key))
IndexError: Individual index(50) out of range

**Comment by LoveSophia** [comment]
大神您好，我们向用这个库来解决带约束项的优化问题，遇到不满足的情况的基因直接淘汰，请问这个用您的库做的话怎么才比较好实现呢？

**Comment by abcgreat11** [comment]
> 大神您好，我们向用这个库来解决带约束项的优化问题，遇到不满足的情况的基因直接淘汰，请问这个用您的库做的话怎么才比较好实现呢？

可以加我QQ：542278416详细交流一下吗？我最近也在学习使用Python遗传算法工具箱。
