### ISSUE TITLE
ImportError: cannot import name log2

### ISSUE THREAD

**Issue by Mathadon** [PytLab/gaft#3]
I'm getting following error using python 2.7.6:
```
Traceback (most recent call last):
  File "xxx", line 32, in <module>
    from gaft import GAEngine
  File "/usr/local/lib/python2.7/dist-packages/gaft/__init__.py", line 4, in <module>
    from .engine import GAEngine
  File "/usr/local/lib/python2.7/dist-packages/gaft/engine.py", line 15, in <module>
    from .components import GAIndividual, GAPopulation
  File "/usr/local/lib/python2.7/dist-packages/gaft/components/__init__.py", line 1, in <module>
    from .individual import GAIndividual
  File "/usr/local/lib/python2.7/dist-packages/gaft/components/individual.py", line 4, in <module>
    from math import log2
ImportError: cannot import name log2
``` 

I suppose that Python 2.7.6 is not supported by gaft? It would make sense to mention this (more) clearly on the front page :)

**Comment by PytLab** [comment]
Yes, GAFT don't support Python 2.x. I've mentioned this using the Python3 badge in README.rst. So it's suggested to use Python3.x to run gaft applications :)

![wx20171016-222935](https://user-images.githubusercontent.com/8553710/31617645-5c494164-b255-11e7-92cc-bac782661740.png)


Thanks for your advice, i will mention it more clearly in README.

**Comment by Mathadon** [comment]
Thanks! Fyi: installation went smoothly for me once I installed openmpi. Looking forward to find out about the other usability aspects :)

**Comment by zhangxuanszx** [comment]
> I'm getting following error using python 2.7.6:
> 
> ```
> Traceback (most recent call last):
>   File "xxx", line 32, in <module>
>     from gaft import GAEngine
>   File "/usr/local/lib/python2.7/dist-packages/gaft/__init__.py", line 4, in <module>
>     from .engine import GAEngine
>   File "/usr/local/lib/python2.7/dist-packages/gaft/engine.py", line 15, in <module>
>     from .components import GAIndividual, GAPopulation
>   File "/usr/local/lib/python2.7/dist-packages/gaft/components/__init__.py", line 1, in <module>
>     from .individual import GAIndividual
>   File "/usr/local/lib/python2.7/dist-packages/gaft/components/individual.py", line 4, in <module>
>     from math import log2
> ImportError: cannot import name log2
> ```
> 
> I suppose that Python 2.7.6 is not supported by gaft? It would make sense to mention this (more) clearly on the front page :)

Hi, do you know the GA in Python2.7?
