### ISSUE TITLE
运行例子报错

### ISSUE THREAD

**Issue by iceiceiceee** [PytLab/gaft#31]
在win10+py3.5上安装，mpi测试用例正常
![image](https://user-images.githubusercontent.com/32871827/48416476-4641fc00-e78b-11e8-9b85-e1dca0f6ab22.png)
运行例子时，报错：
![image](https://user-images.githubusercontent.com/32871827/48416682-d122f680-e78b-11e8-9afa-114abe9f093e.png)

请问是什么原因？
谢谢！

**Comment by abcgreat11** [comment]
> 在win10+py3.5上安装，mpi测试用例正常
> ![image](https://user-images.githubusercontent.com/32871827/48416476-4641fc00-e78b-11e8-9b85-e1dca0f6ab22.png)
> 运行例子时，报错：
> ![image](https://user-images.githubusercontent.com/32871827/48416682-d122f680-e78b-11e8-9afa-114abe9f093e.png)
> 
> 请问是什么原因？
> 谢谢！

。。我也遇到这个问题，请问解决了吗？另外可以加我QQ：542278416详细交流一下吗？我最近也在学习使用Python进化算法工具箱。

**Comment by lilyef2000** [comment]
运行例子还是报错。
C:\Users\Administrator\Envs\py3MachineLearning\Scripts\python.exe D:/personal/Mathematical_modeling/genetic_algorithm.py
Traceback (most recent call last):
  File "D:/personal/Mathematical_modeling/genetic_algorithm.py", line 48, in <module>
    engine.run(ng=100)
  File "C:\Users\Administrator\Envs\py3MachineLearning\lib\site-packages\gaft\engine.py", line 45, in profiled_func
    result = func(*args, **kwargs)
  File "C:\Users\Administrator\Envs\py3MachineLearning\lib\site-packages\gaft\engine.py", line 160, in run
    a.setup(ng=ng, engine=self)
  File "C:\Users\Administrator\Envs\py3MachineLearning\lib\site-packages\gaft\mpiutil.py", line 147, in _call_in_master_proc
    if mpi.is_master:
NameError: name 'mpi' is not defined
麻烦您帮忙看下这是什么问题呢？

engine.py

# Imports for profiling.
import cProfile
import pstats
import os

from .components import IndividualBase, Population
from .plugin_interfaces.operators import Selection, Crossover, Mutation
from .plugin_interfaces.analysis import OnTheFlyAnalysis
from .mpiutil import MPIUtil

mpi = MPIUtil()

mpiutile.py

def master_only(func):
    ''' Decorator to limit a function to be called only in master process in MPI env.
    '''
    @wraps(func)
    def _call_in_master_proc(*args, **kwargs):
        if mpi.is_master:
            return func(*args, **kwargs)

    return _call_in_master_proc

**Comment by PytLab** [comment]
H

**Comment by hoboly** [comment]
https://github.com/PytLab/gaft/commit/105a5ff7bc2a346913876fcd75d5a2135082328f

pip in install 也有問題, 人手條改  C:\ProgramData\Anaconda3\Lib\site-packages\gaft\mpiutil.py 後就無事

**Comment by PytLab** [comment]
可以通过pip install 安装 0.5.7版本，bug已修复
