### ISSUE TITLE
并行问题

### ISSUE THREAD

**Issue by l976308589** [PytLab/gaft#36]
您好:
      我在笔记本上尝试，运行后CPU一直在25%左右。很显然没有并行，请问
      1.并行需要额外配置吗?
      2.GAFT的并行仅仅适用于集群？
谢谢您

**Comment by PytLab** [comment]
你好，请问你是如何执行的？是用mpiexec或者mpirun吗？

**Comment by l976308589** [comment]
是我的错误，我直接在pycharm中运行，没有使用mpirun
打扰您了
