### ISSUE TITLE
多进程运行时，请问如何仅仅让主程序执行一些log文件？

### ISSUE THREAD

**Issue by TheSilverLinings** [PytLab/gaft#56]
如题，请问博主是如何让主进程执行 创建文件，创建log文件，而其他进程不执行这些操作？如果将MPI封装到另一个类中，又要怎么运行程序？还是用mpiexec -n 5 python xx.py 吗？

**Comment by PytLab** [comment]
你可以使用定义 analysis callback的时候设置`master_only=1`来强制只在主进程执行，参考: https://github.com/PytLab/gaft/blob/master/examples/ex01/ex01.py#L47
