### ISSUE TITLE
程序能否把最好的那组参数直接return？

### ISSUE THREAD

**Issue by rogerszhou** [PytLab/gaft#6]
hello小伙伴～程序能否直接把最好的那组参数，即Optimal solution直接return？或者是写成csv文件。那样的话其他程序就可以直接使用函数return的结果了，谢谢。

**Comment by PytLab** [comment]
你好，gaft主要是想设计成一个通用的框架，为了保持灵活性没有在`GAEngine.run`中返回固定的值，但是每一步迭代结束后的种群都是保存在`engine`中的，种群对象也提供了相应的接口来返回最优个体，便可以得到最优解的值。这也是为了方便编写On-the-fly插件，你可以参考项目中内置的分析插件来处理运行中以及优化后的所有相关数据（包括控制台输出以及保存等）。https://github.com/PytLab/gaft/tree/master/gaft/analysis
