### ISSUE TITLE
Error "Microsoft Visual C++ 14.0 is required. " when installing mpi4py

### ISSUE THREAD

**Issue by woaik110** [PytLab/gaft#7]
env: Anaconda 3 for python 3.5.2.  Windows 10  64x 
when installing graft using "python setup.py install"
encounterd this error "Microsoft Visual C++ 14.0 is required." when installing mpi4py.
then after installing mpi4py using this " mpi4py-2.0.0-cp35-none-win_amd64.whl" from https://pypi.python.org/pypi/mpi4py/  for my own env.  and then do the "python setup.py install" again.
Then it went well. might help.

**Comment by PytLab** [comment]
MSVC compiler is required to compile MPI implementation when installing mpi4py. You should install the Microsoft Visual C++ and MPICH firstly, and then try to `pip install mpi4py`.

The installation instruction for mpi version, see https://github.com/PytLab/gaft/blob/master/INSTALL.md
