### ISSUE TITLE
并行化有一些疑问

### ISSUE THREAD

**Issue by a367** [PytLab/gaft#9]
首先感谢作者能提供这么优秀的开源库供大家学习！我在看readme的时候，没有看到如何进行并行化的内容，翻看了example的代码也没有找到，看了关于mip的相关内容后，我猜测是用
```mpiexec -n 10 python  code.py```
这样来开启10个进程来运行，不知道是否如此？

**Comment by PytLab** [comment]
是的，通过`mpirun -np 2 python yourscript.py`启动两个进程执行，gaft的`GAEngine`会在内部进行通信并行执行。
